openapi: 3.0.3
info:
  title: Bank Argent API documentation 1.0.0
  description: |-
   Contains all available API endpoints in this codebase
    Some useful links:
    - [Team of service](https://smartbear.com/terms-of-use/)

  termsOfService: http://swagger.io/terms/
paths:
  /user/transaction:
    get:
      tags:
        - transaction
      summary: get transaction
      description: This can only be done by the logged in user.
      operationId: get all transaction
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true

      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/allTransaction'         
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    post:
      tags:
        - transaction
      summary: Creates new transaction
      description: Creates new transaction
      operationId: Creates new transaction
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
      requestBody: 
        description: add new transaction
        content:
          application/json:
              schema:
                 $ref: '#/components/schemas/addTransaction'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/allTransaction'          
            application/xml:
              schema:
                $ref: '#/components/schemas/allTransaction'
        default:
          description: successful operation

  /user/transaction/{id}:
    get:
      tags:
        - transaction
      summary: get transaction
      description: This can only be done by the logged in user.
      operationId: get one transaction
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
        - name: id
          in: path
          description: The id that needs to be deleted
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/allTransaction'         
            application/xml:
              schema:
                $ref: '#/components/schemas/allTransaction'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      tags:
        - transaction
      summary: Update an existing transtaction
      description: Update an existing transaction by Id
      operationId: updateTransaction
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
        - name: id
          in: header
          description: The id that needs to be update
          required: true
        - name: body
          in: header
          description: Update transaction attributes
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/addTransaction'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/allTransaction'         
            application/xml:
              schema:
                $ref: '#/components/schemas/allTransaction'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    
    delete:
      tags:
        - transaction
      summary: Delete transaction
      description: This can only be done by the logged in user.
      operationId: deleteTransaction
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
        - name: id
          in: path
          description: The id that needs to be deleted
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Delete transaction successully
        '400':
          description: Invalid Fields
        '500':
          description: 	Internal Server Error
components:
  schemas:
    addTransaction :
      type: object
      properties:
        Category:
          type: string
          example: string
        Note:
          type: string
          example: string
    allTransaction:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 0
        Category:
          type: string
          example: string
        Note:
          type: string
          example: string
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header